export const TYPES_LIST_VOTES = {
    LOADING_LIST_VOTES: 'LOADING_LIST_VOTES',
    LOADED_LIST_VOTES: 'LOADED_LIST_VOTES',
    ERROR_LIST_VOTES: 'ERROR_LIST_VOTES'
}

export const CREATE_VOTE = 'CREATE_VOTE'
export const TOGGLE_VOTE = 'TOGGLE_VOTE'
export const DELETE_VOTE = 'DELETE_VOTE'
export const INCREMENT_VOTE = 'INCREMENT_VOTE'
export const DECREMENT_VOTE = 'DECREMENT_VOTE'